import { DailyPrompt } from '../types';

export const INITIAL_DAILY_PROMPTS: DailyPrompt[] = [
  // CATEGRORÍA 1: RUIDO (12 prompts)
  {
    id: 'prompt-r-1',
    prompt_text: '¿Qué pensamiento recurrente has estado repitiendo en bucle durante las últimas 48 horas sin darte cuenta?',
    category: 'Ruido',
    week: 1,
    difficulty: 'suave',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'prompt-r-2',
    prompt_text: '¿Qué distracción externa estás usando deliberadamente para no quedarte a solas con tus pensamientos?',
    category: 'Ruido',
    week: 1,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-01-02T00:00:00Z',
  },
  {
    id: 'prompt-r-3',
    prompt_text: '¿Qué conversación inconclusa sigue consumiendo batería en el fondo de tu mente?',
    category: 'Ruido',
    week: 1,
    difficulty: 'suave',
    active: true,
    created_at: '2026-01-03T00:00:00Z',
  },
  {
    id: 'prompt-r-4',
    prompt_text: 'Si pudieras apagar una sola preocupación durante el día de hoy, ¿cuál traería el mayor alivio?',
    category: 'Ruido',
    week: 1,
    difficulty: 'suave',
    active: true,
    created_at: '2026-01-04T00:00:00Z',
  },
  {
    id: 'prompt-r-5',
    prompt_text: '¿Qué expectativas ajenas estás tratando de satisfacer en este momento que no te corresponden?',
    category: 'Ruido',
    week: 1,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-01-05T00:00:00Z',
  },
  {
    id: 'prompt-r-6',
    prompt_text: '¿En qué momentos de tu día sientes que tu atención se fractura por completo?',
    category: 'Ruido',
    week: 1,
    difficulty: 'suave',
    active: true,
    created_at: '2026-01-06T00:00:00Z',
  },
  {
    id: 'prompt-r-7',
    prompt_text: '¿Cuál es la urgencia fabricada que hoy estás tratando como si fuera de vida o muerte?',
    category: 'Ruido',
    week: 1,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-01-07T00:00:00Z',
  },
  {
    id: 'prompt-r-8',
    prompt_text: 'Describe cómo se siente tu cuerpo cuando estás saturado de información y estímulos.',
    category: 'Ruido',
    week: 1,
    difficulty: 'suave',
    active: true,
    created_at: '2026-01-08T00:00:00Z',
  },
  {
    id: 'prompt-r-9',
    prompt_text: '¿Qué estás consumiendo en redes o noticias que alimenta tu cinismo en lugar de tu discernimiento?',
    category: 'Ruido',
    week: 1,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-01-09T00:00:00Z',
  },
  {
    id: 'prompt-r-10',
    prompt_text: 'Si le bajaras el volumen al ruido de tu alrededor, ¿qué verdad incómoda empezaría a sonar?',
    category: 'Ruido',
    week: 1,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: 'prompt-r-11',
    prompt_text: '¿A qué compromiso dijiste que sí por complacer, cuando todo tu interior decía que no?',
    category: 'Ruido',
    week: 1,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-01-11T00:00:00Z',
  },
  {
    id: 'prompt-r-12',
    prompt_text: '¿Qué tarea secundaria estás usando para procrastinar la decisión más pesada del día?',
    category: 'Ruido',
    week: 1,
    difficulty: 'suave',
    active: true,
    created_at: '2026-01-12T00:00:00Z',
  },

  // CATEGORÍA 2: EMOCIONES (12 prompts)
  {
    id: 'prompt-e-1',
    prompt_text: '¿Qué emoción estás intentando enterrar o fingir que no existe para no parecer débil?',
    category: 'Emociones',
    week: 1,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-01-13T00:00:00Z',
  },
  {
    id: 'prompt-e-2',
    prompt_text: '¿Dónde se aloja la tensión en tu cuerpo hoy: garganta, hombros, pecho o estómago?',
    category: 'Emociones',
    week: 1,
    difficulty: 'suave',
    active: true,
    created_at: '2026-01-14T00:00:00Z',
  },
  {
    id: 'prompt-e-3',
    prompt_text: '¿Sientes tristeza por una pérdida reciente o un anhelo que aún no se ha cumplido?',
    category: 'Emociones',
    week: 1,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-01-15T00:00:00Z',
  },
  {
    id: 'prompt-e-4',
    prompt_text: '¿Qué injusticia percibida te está provocando una ira que aún no has procesado?',
    category: 'Emociones',
    week: 1,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-01-16T00:00:00Z',
  },
  {
    id: 'prompt-e-5',
    prompt_text: '¿Hay algún sentimiento de vergüenza relacionado con un error que cometiste recientemente?',
    category: 'Emociones',
    week: 1,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-01-17T00:00:00Z',
  },
  {
    id: 'prompt-e-6',
    prompt_text: 'Si tu cansancio de hoy pudiera hablar con total franqueza, ¿qué te pediría?',
    category: 'Emociones',
    week: 1,
    difficulty: 'suave',
    active: true,
    created_at: '2026-01-18T00:00:00Z',
  },
  {
    id: 'prompt-e-7',
    prompt_text: '¿Te permites experimentar alegría genuina sin esperar inmediatamente que algo malo suceda?',
    category: 'Emociones',
    week: 1,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-01-19T00:00:00Z',
  },
  {
    id: 'prompt-e-8',
    prompt_text: '¿En qué momentos te sientes profundamente solo, incluso estando rodeado de gente?',
    category: 'Emociones',
    week: 1,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-01-20T00:00:00Z',
  },
  {
    id: 'prompt-e-9',
    prompt_text: '¿Qué culpa innecesaria sigues arrastrando sobre algo que ya no puedes cambiar?',
    category: 'Emociones',
    week: 1,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-01-21T00:00:00Z',
  },
  {
    id: 'prompt-e-10',
    prompt_text: '¿Cómo reaccionas cuando sientes envidia o comparación hacia el éxito de otro?',
    category: 'Emociones',
    week: 1,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-01-22T00:00:00Z',
  },
  {
    id: 'prompt-e-11',
    prompt_text: 'Nombra sin juzgar el estado de ánimo con el que despertaste hoy.',
    category: 'Emociones',
    week: 1,
    difficulty: 'suave',
    active: true,
    created_at: '2026-01-23T00:00:00Z',
  },
  {
    id: 'prompt-e-12',
    prompt_text: '¿Qué te duele en este momento que nadie a tu alrededor parece notar?',
    category: 'Emociones',
    week: 1,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-01-24T00:00:00Z',
  },

  // CATEGORÍA 3: VISIÓN (12 prompts)
  {
    id: 'prompt-v-1',
    prompt_text: 'Si dentro de tres años tu vida fuera verdaderamente fecunda y en paz, ¿cómo empezaría un martes normal?',
    category: 'Visión',
    week: 2,
    difficulty: 'suave',
    active: true,
    created_at: '2026-01-25T00:00:00Z',
  },
  {
    id: 'prompt-v-2',
    prompt_text: '¿Qué clase de padre, cónyuge, hermano o amigo quieres ser recordado como dentro de 20 años?',
    category: 'Visión',
    week: 2,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-01-26T00:00:00Z',
  },
  {
    id: 'prompt-v-3',
    prompt_text: '¿Qué proyecto o vocación profunda abandonarías tu zona de confort para construir?',
    category: 'Visión',
    week: 2,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-01-27T00:00:00Z',
  },
  {
    id: 'prompt-v-4',
    prompt_text: 'Describe el tipo de madurez de carácter que desearías poseer en momentos de crisis.',
    category: 'Visión',
    week: 2,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-01-28T00:00:00Z',
  },
  {
    id: 'prompt-v-5',
    prompt_text: '¿Qué relación te gustaría ver restaurada, fortalecida o profundamente unida?',
    category: 'Visión',
    week: 2,
    difficulty: 'suave',
    active: true,
    created_at: '2026-01-29T00:00:00Z',
  },
  {
    id: 'prompt-v-6',
    prompt_text: '¿Qué significa para ti el éxito real, despojado de lo que dice la sociedad o el dinero?',
    category: 'Visión',
    week: 2,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-01-30T00:00:00Z',
  },
  {
    id: 'prompt-v-7',
    prompt_text: 'Si tu salud física y mental estuvieran en su mejor estado, ¿qué hábitos sostendrían ese ritmo?',
    category: 'Visión',
    week: 2,
    difficulty: 'suave',
    active: true,
    created_at: '2026-01-31T00:00:00Z',
  },
  {
    id: 'prompt-v-8',
    prompt_text: '¿Cómo imaginas tu vida de oración y comunión con Dios dentro de un año?',
    category: 'Visión',
    week: 2,
    difficulty: 'suave',
    active: true,
    created_at: '2026-02-01T00:00:00Z',
  },
  {
    id: 'prompt-v-9',
    prompt_text: '¿Qué legado tangible te gustaría dejar en tu comunidad o familia?',
    category: 'Visión',
    week: 2,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-02-02T00:00:00Z',
  },
  {
    id: 'prompt-v-10',
    prompt_text: 'Si supieras que Dios respalda tu esfuerzo, ¿qué sueño dejarías de posponer por miedo?',
    category: 'Visión',
    week: 2,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-02-03T00:00:00Z',
  },
  {
    id: 'prompt-v-11',
    prompt_text: '¿Qué estándares personales no negociables quieres que rijan tus decisiones diarias?',
    category: 'Visión',
    week: 2,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-02-04T00:00:00Z',
  },
  {
    id: 'prompt-v-12',
    prompt_text: '¿Cómo sería tu hogar si la paz y la gracia fueran la atmósfera predominante?',
    category: 'Visión',
    week: 2,
    difficulty: 'suave',
    active: true,
    created_at: '2026-02-05T00:00:00Z',
  },

  // CATEGORÍA 4: OBSTÁCULOS (12 prompts)
  {
    id: 'prompt-o-1',
    prompt_text: '¿Cuál es la excusa más inteligente que te cuentas para justificar no avanzar?',
    category: 'Obstáculos',
    week: 3,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-02-06T00:00:00Z',
  },
  {
    id: 'prompt-o-2',
    prompt_text: '¿Qué herida o experiencia del pasado sigues utilizando como coartada en el presente?',
    category: 'Obstáculos',
    week: 3,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-02-07T00:00:00Z',
  },
  {
    id: 'prompt-o-3',
    prompt_text: '¿A qué persona o figura le estás cediendo el poder sobre tu estado de ánimo?',
    category: 'Obstáculos',
    week: 3,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-02-08T00:00:00Z',
  },
  {
    id: 'prompt-o-4',
    prompt_text: '¿De qué manera tu necesidad de perfeccionismo te está paralizando hoy?',
    category: 'Obstáculos',
    week: 3,
    difficulty: 'suave',
    active: true,
    created_at: '2026-02-09T00:00:00Z',
  },
  {
    id: 'prompt-o-5',
    prompt_text: '¿Qué hábito nocivo de escape utilizas cuando las emociones se vuelven intensas?',
    category: 'Obstáculos',
    week: 3,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-02-10T00:00:00Z',
  },
  {
    id: 'prompt-o-6',
    prompt_text: '¿Qué conversación difícil estás evitando porque temes el rechazo o el conflicto?',
    category: 'Obstáculos',
    week: 3,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-02-11T00:00:00Z',
  },
  {
    id: 'prompt-o-7',
    prompt_text: '¿En qué área de tu vida el orgullo te impide pedir ayuda con humildad?',
    category: 'Obstáculos',
    week: 3,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-02-12T00:00:00Z',
  },
  {
    id: 'prompt-o-8',
    prompt_text: '¿Qué mentira creíste sobre tu propia capacidad que hoy opera como un techo invisible?',
    category: 'Obstáculos',
    week: 3,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-02-13T00:00:00Z',
  },
  {
    id: 'prompt-o-9',
    prompt_text: '¿Qué te asusta de triunfar de verdad y asumir la responsabilidad correspondiente?',
    category: 'Obstáculos',
    week: 3,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-02-14T00:00:00Z',
  },
  {
    id: 'prompt-o-10',
    prompt_text: '¿Cuánto tiempo al día pierdes reaccionando al mundo en vez de liderar tu propia vida?',
    category: 'Obstáculos',
    week: 3,
    difficulty: 'suave',
    active: true,
    created_at: '2026-02-15T00:00:00Z',
  },
  {
    id: 'prompt-o-11',
    prompt_text: '¿A qué resentimiento te sigues aferrando como si castigara a la otra persona?',
    category: 'Obstáculos',
    week: 3,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-02-16T00:00:00Z',
  },
  {
    id: 'prompt-o-12',
    prompt_text: '¿Qué comodidad mediocre te está impidiendo buscar la excelencia que sabes que puedes dar?',
    category: 'Obstáculos',
    week: 3,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-02-17T00:00:00Z',
  },

  // CATEGORÍA 5: ACCIÓN (12 prompts)
  {
    id: 'prompt-a-1',
    prompt_text: '¿Cuál es la acción más pequeña, concreta e inmediata que puedes ejecutar en los próximos 60 minutos?',
    category: 'Acción',
    week: 4,
    difficulty: 'suave',
    active: true,
    created_at: '2026-02-18T00:00:00Z',
  },
  {
    id: 'prompt-a-2',
    prompt_text: '¿Qué asunto pendiente puedes resolver hoy mismo para liberar espacio mental?',
    category: 'Acción',
    week: 4,
    difficulty: 'suave',
    active: true,
    created_at: '2026-02-19T00:00:00Z',
  },
  {
    id: 'prompt-a-3',
    prompt_text: '¿A quién necesitas escribirle un mensaje directo y honesto antes de que termine el día?',
    category: 'Acción',
    week: 4,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-02-20T00:00:00Z',
  },
  {
    id: 'prompt-a-4',
    prompt_text: '¿Qué límite sano tienes que establecer hoy para proteger tu paz y tu tiempo?',
    category: 'Acción',
    week: 4,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-02-21T00:00:00Z',
  },
  {
    id: 'prompt-a-5',
    prompt_text: 'Si solo pudieras lograr una sola cosa valiosa hoy, ¿cuál justificaría el día entero?',
    category: 'Acción',
    week: 4,
    difficulty: 'suave',
    active: true,
    created_at: '2026-02-22T00:00:00Z',
  },
  {
    id: 'prompt-a-6',
    prompt_text: '¿Qué hábito simple vas a empezar o reanudar hoy sin buscar la perfección?',
    category: 'Acción',
    week: 4,
    difficulty: 'suave',
    active: true,
    created_at: '2026-02-23T00:00:00Z',
  },
  {
    id: 'prompt-a-7',
    prompt_text: '¿Qué decisión difícil que vienes posponiendo vas a tomar hoy pase lo que pase?',
    category: 'Acción',
    week: 4,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-02-24T00:00:00Z',
  },
  {
    id: 'prompt-a-8',
    prompt_text: '¿Cómo vas a honrar hoy tu compromiso con las personas que dependen de tu liderazgo?',
    category: 'Acción',
    week: 4,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-02-25T00:00:00Z',
  },
  {
    id: 'prompt-a-9',
    prompt_text: '¿Qué debes eliminar de tu agenda de hoy porque simplemente no aporta valor?',
    category: 'Acción',
    week: 4,
    difficulty: 'suave',
    active: true,
    created_at: '2026-02-26T00:00:00Z',
  },
  {
    id: 'prompt-a-10',
    prompt_text: '¿Qué gesto de generosidad discreta y sin aplausos puedes tener hoy con alguien?',
    category: 'Acción',
    week: 4,
    difficulty: 'suave',
    active: true,
    created_at: '2026-02-27T00:00:00Z',
  },
  {
    id: 'prompt-a-11',
    prompt_text: '¿A qué tentación recurrente vas a decirle firmemente "no" hoy?',
    category: 'Acción',
    week: 4,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-02-28T00:00:00Z',
  },
  {
    id: 'prompt-a-12',
    prompt_text: 'Escribe tu compromiso principal de hoy en una sola frase de no más de 10 palabras.',
    category: 'Acción',
    week: 4,
    difficulty: 'suave',
    active: true,
    created_at: '2026-03-01T00:00:00Z',
  },

  // CATEGORÍA 6: RELACIONES (11 prompts)
  {
    id: 'prompt-rel-1',
    prompt_text: '¿A quién le debes una disculpa sincera sin justificaciones ni excusas?',
    category: 'Relaciones',
    week: 2,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-03-02T00:00:00Z',
  },
  {
    id: 'prompt-rel-2',
    prompt_text: '¿Estás escuchando a las personas más importantes de tu vida o solo esperando tu turno para hablar?',
    category: 'Relaciones',
    week: 2,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-03-03T00:00:00Z',
  },
  {
    id: 'prompt-rel-3',
    prompt_text: '¿A qué persona estás dando por sentada y merece hoy unas palabras de aprecio?',
    category: 'Relaciones',
    week: 2,
    difficulty: 'suave',
    active: true,
    created_at: '2026-03-04T00:00:00Z',
  },
  {
    id: 'prompt-rel-4',
    prompt_text: '¿Qué relación te está desgastando porque no has puesto límites claros y firmes?',
    category: 'Relaciones',
    week: 3,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-03-05T00:00:00Z',
  },
  {
    id: 'prompt-rel-5',
    prompt_text: '¿Cómo influye tu estado de ánimo no resuelto en el tono con el que tratas a tu familia?',
    category: 'Relaciones',
    week: 1,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-03-06T00:00:00Z',
  },
  {
    id: 'prompt-rel-6',
    prompt_text: '¿Con quién necesitas tener una charla de rendición de cuentas honesta esta semana?',
    category: 'Relaciones',
    week: 4,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-03-07T00:00:00Z',
  },
  {
    id: 'prompt-rel-7',
    prompt_text: '¿Qué herida relacional del pasado estás proyectando involuntariamente en tu pareja o amigos?',
    category: 'Relaciones',
    week: 3,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-03-08T00:00:00Z',
  },
  {
    id: 'prompt-rel-8',
    prompt_text: '¿Quién en tu círculo cercano necesita ánimo urgente y cómo puedes ser tú quien lo provea?',
    category: 'Relaciones',
    week: 2,
    difficulty: 'suave',
    active: true,
    created_at: '2026-03-09T00:00:00Z',
  },
  {
    id: 'prompt-rel-9',
    prompt_text: '¿Te cuesta perdonar porque crees que perdonar significa decir que lo ocurrido no importó?',
    category: 'Relaciones',
    week: 3,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-03-10T00:00:00Z',
  },
  {
    id: 'prompt-rel-10',
    prompt_text: '¿Qué máscara social usas con mayor frecuencia para que los demás piensen que estás bien?',
    category: 'Relaciones',
    week: 1,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-03-11T00:00:00Z',
  },
  {
    id: 'prompt-rel-11',
    prompt_text: '¿Cómo puedes ser un puerto seguro para la vulnerabilidad de quienes te rodean?',
    category: 'Relaciones',
    week: 4,
    difficulty: 'suave',
    active: true,
    created_at: '2026-03-12T00:00:00Z',
  },

  // CATEGORÍA 7: PROPÓSITO (11 prompts)
  {
    id: 'prompt-p-1',
    prompt_text: '¿En qué actividad pierdes la noción del tiempo y sientes que estás sirviendo a algo mayor?',
    category: 'Propósito',
    week: 2,
    difficulty: 'suave',
    active: true,
    created_at: '2026-03-13T00:00:00Z',
  },
  {
    id: 'prompt-p-2',
    prompt_text: '¿Qué problema en el mundo o en tu comunidad te quebranta el corazón cada vez que lo ves?',
    category: 'Propósito',
    week: 2,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-03-14T00:00:00Z',
  },
  {
    id: 'prompt-p-3',
    prompt_text: 'Si el dinero no fuera un factor, ¿en qué invertirías tus mejores horas de energía mental?',
    category: 'Propósito',
    week: 2,
    difficulty: 'suave',
    active: true,
    created_at: '2026-03-15T00:00:00Z',
  },
  {
    id: 'prompt-p-4',
    prompt_text: '¿Qué dones o talentos has dejado enterrados por falta de confianza o pereza?',
    category: 'Propósito',
    week: 3,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-03-16T00:00:00Z',
  },
  {
    id: 'prompt-p-5',
    prompt_text: '¿Qué dolor de tu propia historia podría convertirse en consuelo y guía para otros?',
    category: 'Propósito',
    week: 2,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-03-17T00:00:00Z',
  },
  {
    id: 'prompt-p-6',
    prompt_text: '¿Estás persiguiendo un llamado genuino o simplemente el aplauso y el reconocimiento?',
    category: 'Propósito',
    week: 2,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-03-18T00:00:00Z',
  },
  {
    id: 'prompt-p-7',
    prompt_text: '¿Cómo se conecta tu trabajo ordinario de cada día con el propósito eterno de Dios?',
    category: 'Propósito',
    week: 2,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-03-19T00:00:00Z',
  },
  {
    id: 'prompt-p-8',
    prompt_text: '¿Qué causa estás dispuesto a defender aunque signifique nadar contra la corriente cultural?',
    category: 'Propósito',
    week: 3,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-03-20T00:00:00Z',
  },
  {
    id: 'prompt-p-9',
    prompt_text: '¿Qué estás sembrando hoy que dará fruto cuando ya no estés aquí?',
    category: 'Propósito',
    week: 2,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-03-21T00:00:00Z',
  },
  {
    id: 'prompt-p-10',
    prompt_text: '¿Cuál es la diferencia entre lo que crees que "deberías" hacer y lo que Dios te pide hacer?',
    category: 'Propósito',
    week: 2,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-03-22T00:00:00Z',
  },
  {
    id: 'prompt-p-11',
    prompt_text: '¿Qué te impide dar el siguiente paso en tu vocación: la falta de recursos o la falta de valentía?',
    category: 'Propósito',
    week: 3,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-03-23T00:00:00Z',
  },

  // CATEGORÍA 8: ESPIRITUALIDAD (15 prompts)
  {
    id: 'prompt-esp-1',
    prompt_text: 'Señor, ¿qué verdad sobre mi vida he estado intentando ocultarte a Ti y a mí mismo?',
    category: 'Espiritualidad',
    week: 1,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-03-24T00:00:00Z',
  },
  {
    id: 'prompt-esp-2',
    prompt_text: '¿En qué área de tu vida estás tratando de tener el control absoluto en vez de confiar en Dios?',
    category: 'Espiritualidad',
    week: 1,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-03-25T00:00:00Z',
  },
  {
    id: 'prompt-esp-3',
    prompt_text: 'Si te quedas en silencio durante dos minutos, ¿qué susurro interior comienzas a percibir?',
    category: 'Espiritualidad',
    week: 1,
    difficulty: 'suave',
    active: true,
    created_at: '2026-03-26T00:00:00Z',
  },
  {
    id: 'prompt-esp-4',
    prompt_text: '¿Agradeces a Dios por lo ordinario o solo te acuerdas de orar cuando la tormenta arrecia?',
    category: 'Espiritualidad',
    week: 1,
    difficulty: 'suave',
    active: true,
    created_at: '2026-03-27T00:00:00Z',
  },
  {
    id: 'prompt-esp-5',
    prompt_text: '¿Qué ídolo sutil (comodidad, aprobación, estatus) ha tomado el lugar de Dios en tu corazón?',
    category: 'Espiritualidad',
    week: 3,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-03-28T00:00:00Z',
  },
  {
    id: 'prompt-esp-6',
    prompt_text: '¿Cómo experimentas la gracia de Dios cuando sabes que has fallado miserablemente?',
    category: 'Espiritualidad',
    week: 1,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-03-29T00:00:00Z',
  },
  {
    id: 'prompt-esp-7',
    prompt_text: '¿Qué le estás pidiendo a Dios que cambie en otros que en realidad necesita cambiar en ti?',
    category: 'Espiritualidad',
    week: 3,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-03-30T00:00:00Z',
  },
  {
    id: 'prompt-esp-8',
    prompt_text: 'Escribe una oración sincera de tres líneas reconociendo tu fragilidad humana hoy.',
    category: 'Espiritualidad',
    week: 1,
    difficulty: 'suave',
    active: true,
    created_at: '2026-03-31T00:00:00Z',
  },
  {
    id: 'prompt-esp-9',
    prompt_text: '¿Qué significa descansar verdaderamente en el Señor en medio de una semana exigente?',
    category: 'Espiritualidad',
    week: 1,
    difficulty: 'suave',
    active: true,
    created_at: '2026-04-01T00:00:00Z',
  },
  {
    id: 'prompt-esp-10',
    prompt_text: '¿Sientes que Dios está decepcionado de ti o puedes contemplar su amor incondicional?',
    category: 'Espiritualidad',
    week: 3,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-04-02T00:00:00Z',
  },
  {
    id: 'prompt-esp-11',
    prompt_text: '¿Qué pasaje, promesa o enseñanza espiritual ha sido tu ancla en tiempos recientes?',
    category: 'Espiritualidad',
    week: 2,
    difficulty: 'suave',
    active: true,
    created_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'prompt-esp-12',
    prompt_text: '¿Qué carga que no te corresponde llevar estás dispuesto a entregarle a Dios hoy?',
    category: 'Espiritualidad',
    week: 4,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-04-04T00:00:00Z',
  },
  {
    id: 'prompt-esp-13',
    prompt_text: '¿Cómo se refleja tu fe en la manera en que hablas con quienes no piensan como tú?',
    category: 'Espiritualidad',
    week: 4,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-04-05T00:00:00Z',
  },
  {
    id: 'prompt-esp-14',
    prompt_text: 'En medio de la incertidumbre actual, ¿en qué atributos inmutables de Dios puedes apoyarte?',
    category: 'Espiritualidad',
    week: 2,
    difficulty: 'suave',
    active: true,
    created_at: '2026-04-06T00:00:00Z',
  },
  {
    id: 'prompt-esp-15',
    prompt_text: 'Pide hoy a Dios sabiduría para distinguir lo urgente de lo que tiene peso eterno.',
    category: 'Espiritualidad',
    week: 4,
    difficulty: 'suave',
    active: true,
    created_at: '2026-04-07T00:00:00Z',
  },

  // CATEGORÍA 9: DISCIPLINA (15 prompts)
  {
    id: 'prompt-d-1',
    prompt_text: '¿En qué área de tu vida sabes con exactitud qué hacer pero no lo estás ejecutando?',
    category: 'Disciplina',
    week: 4,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-04-08T00:00:00Z',
  },
  {
    id: 'prompt-d-2',
    prompt_text: '¿Qué costo estás pagando a largo plazo por buscar alivio y gratificación instantánea a corto plazo?',
    category: 'Disciplina',
    week: 3,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-04-09T00:00:00Z',
  },
  {
    id: 'prompt-d-3',
    prompt_text: '¿Tu rutina matutina te posiciona para la victoria o para la dispersión y la ansiedad?',
    category: 'Disciplina',
    week: 1,
    difficulty: 'suave',
    active: true,
    created_at: '2026-04-10T00:00:00Z',
  },
  {
    id: 'prompt-d-4',
    prompt_text: '¿Cuál es el disparador ambiental que casi siempre te hace caer en malos hábitos?',
    category: 'Disciplina',
    week: 3,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-04-11T00:00:00Z',
  },
  {
    id: 'prompt-d-5',
    prompt_text: '¿Qué micro-hábito de dos minutos podrías sostener todos los días sin excusa durante el próximo mes?',
    category: 'Disciplina',
    week: 1,
    difficulty: 'suave',
    active: true,
    created_at: '2026-04-12T00:00:00Z',
  },
  {
    id: 'prompt-d-6',
    prompt_text: '¿Cumples las promesas que te haces a ti mismo con la misma seriedad con que cumples a tus clientes o jefes?',
    category: 'Disciplina',
    week: 4,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-04-13T00:00:00Z',
  },
  {
    id: 'prompt-d-7',
    prompt_text: '¿Cómo manejas la fatiga mental: recurres a pantallas o buscas descanso reparador para tu alma?',
    category: 'Disciplina',
    week: 1,
    difficulty: 'suave',
    active: true,
    created_at: '2026-04-14T00:00:00Z',
  },
  {
    id: 'prompt-d-8',
    prompt_text: '¿Qué compromiso asumido la semana pasada abandonaste tan pronto se puso incómodo?',
    category: 'Disciplina',
    week: 4,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-04-15T00:00:00Z',
  },
  {
    id: 'prompt-d-9',
    prompt_text: '¿De qué manera la autocompasión mal entendida se ha convertido en permisividad contigo mismo?',
    category: 'Disciplina',
    week: 3,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-04-16T00:00:00Z',
  },
  {
    id: 'prompt-d-10',
    prompt_text: 'Escribe tres reglas simples para proteger las primeras dos horas de tu día laboral.',
    category: 'Disciplina',
    week: 4,
    difficulty: 'suave',
    active: true,
    created_at: '2026-04-17T00:00:00Z',
  },
  {
    id: 'prompt-d-11',
    prompt_text: '¿Cuál es la relación entre tu orden físico (espacio de trabajo, cuarto) y tu claridad mental?',
    category: 'Disciplina',
    week: 1,
    difficulty: 'suave',
    active: true,
    created_at: '2026-04-18T00:00:00Z',
  },
  {
    id: 'prompt-d-12',
    prompt_text: '¿Qué sacrificio necesario estás dispuesto a hacer esta semana para acercarte a tu visión?',
    category: 'Disciplina',
    week: 4,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-04-19T00:00:00Z',
  },
  {
    id: 'prompt-d-13',
    prompt_text: '¿A qué horas de la noche deberías apagar tus pantallas para asegurar un descanso regenerador?',
    category: 'Disciplina',
    week: 1,
    difficulty: 'suave',
    active: true,
    created_at: '2026-04-20T00:00:00Z',
  },
  {
    id: 'prompt-d-14',
    prompt_text: 'La consistencia en el diario de hoy es un acto de carácter. ¿Qué harás para no romperla mañana?',
    category: 'Disciplina',
    week: 1,
    difficulty: 'suave',
    active: true,
    created_at: '2026-04-21T00:00:00Z',
  },
  {
    id: 'prompt-d-15',
    prompt_text: 'Haz hoy el trabajo difícil primero, antes de que el ruido del mundo te convenza de posponerlo.',
    category: 'Disciplina',
    week: 4,
    difficulty: 'suave',
    active: true,
    created_at: '2026-04-22T00:00:00Z',
  }
,
  {
    id: 'prompt-ext-103',
    prompt_text: '¿Qué pensamiento no solicitado invadió tus primeros cinco minutos de vigilia hoy?',
    category: 'Ruido',
    week: 1,
    difficulty: 'suave',
    active: true,
    created_at: '2026-05-20T00:00:00Z',
  },
  {
    id: 'prompt-ext-104',
    prompt_text: '¿Cuántas veces al día desbloqueas el teléfono sin un propósito claro y qué estás intentando esquivar?',
    category: 'Ruido',
    week: 1,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-05-21T00:00:00Z',
  },
  {
    id: 'prompt-ext-105',
    prompt_text: '¿Qué noticia, polémica o debate ajeno te ha robado energía que necesitabas para tu vocación?',
    category: 'Ruido',
    week: 1,
    difficulty: 'suave',
    active: true,
    created_at: '2026-05-22T00:00:00Z',
  },
  {
    id: 'prompt-ext-106',
    prompt_text: 'Si cerraras los ojos durante tres minutos ahora mismo, ¿cuál es el primer grito que emerge del silencio?',
    category: 'Ruido',
    week: 1,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-05-23T00:00:00Z',
  },
  {
    id: 'prompt-ext-107',
    prompt_text: '¿Qué compromiso asumido por compromiso social te gustaría cancelar hoy mismo?',
    category: 'Ruido',
    week: 1,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-05-24T00:00:00Z',
  },
  {
    id: 'prompt-ext-108',
    prompt_text: '¿En qué espacio físico de tu hogar o trabajo reina un desorden que refleja tu estado mental?',
    category: 'Ruido',
    week: 1,
    difficulty: 'suave',
    active: true,
    created_at: '2026-05-25T00:00:00Z',
  },
  {
    id: 'prompt-ext-109',
    prompt_text: '¿Qué opinión de alguien que no respeta tus valores ha tenido demasiado peso en tus decisiones recientes?',
    category: 'Ruido',
    week: 1,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-05-26T00:00:00Z',
  },
  {
    id: 'prompt-ext-110',
    prompt_text: '¿Qué prisa ficticia te estás autoimponiendo en un proceso que por naturaleza requiere tiempo?',
    category: 'Ruido',
    week: 1,
    difficulty: 'suave',
    active: true,
    created_at: '2026-05-27T00:00:00Z',
  },
  {
    id: 'prompt-ext-111',
    prompt_text: '¿Qué tarea de bajo impacto estás usando para sentirte ocupado y evitar el trabajo esencial?',
    category: 'Ruido',
    week: 1,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-05-28T00:00:00Z',
  },
  {
    id: 'prompt-ext-112',
    prompt_text: 'Si tuvieras que explicarle a un niño tu ritmo de vida actual, ¿te sentirías en paz con su respuesta?',
    category: 'Ruido',
    week: 1,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-05-01T00:00:00Z',
  },
  {
    id: 'prompt-ext-113',
    prompt_text: '¿Cuál es el sonido más restaurador que has olvidado escuchar esta semana?',
    category: 'Ruido',
    week: 1,
    difficulty: 'suave',
    active: true,
    created_at: '2026-05-02T00:00:00Z',
  },
  {
    id: 'prompt-ext-114',
    prompt_text: '¿Qué ruido estás tolerando en tu entorno que podrías apagar con un simple límite?',
    category: 'Ruido',
    week: 1,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-05-03T00:00:00Z',
  },
  {
    id: 'prompt-ext-115',
    prompt_text: '¿Cuál es la emoción predominante que llevas en el pecho mientras respiras en este instante?',
    category: 'Emociones',
    week: 1,
    difficulty: 'suave',
    active: true,
    created_at: '2026-05-04T00:00:00Z',
  },
  {
    id: 'prompt-ext-116',
    prompt_text: '¿Qué tristeza no llorada has intentado disimular detrás de una productividad excesiva?',
    category: 'Emociones',
    week: 1,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-05-05T00:00:00Z',
  },
  {
    id: 'prompt-ext-117',
    prompt_text: '¿En qué parte exacta de tu cuerpo se aloja la tensión cuando sientes frustración?',
    category: 'Emociones',
    week: 1,
    difficulty: 'suave',
    active: true,
    created_at: '2026-05-06T00:00:00Z',
  },
  {
    id: 'prompt-ext-118',
    prompt_text: '¿Qué ira guardada hacia alguien cercano se está pudriendo en forma de cinismo o sarcasmo?',
    category: 'Emociones',
    week: 1,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-05-07T00:00:00Z',
  },
  {
    id: 'prompt-ext-119',
    prompt_text: '¿Qué miedo infantil a no ser suficiente sigue operando cuando te enfrentas a una oportunidad grande?',
    category: 'Emociones',
    week: 2,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-05-08T00:00:00Z',
  },
  {
    id: 'prompt-ext-120',
    prompt_text: '¿Cuál fue el último momento en que sentiste una alegría desinteresada y libre de culpa?',
    category: 'Emociones',
    week: 2,
    difficulty: 'suave',
    active: true,
    created_at: '2026-05-09T00:00:00Z',
  },
  {
    id: 'prompt-ext-121',
    prompt_text: '¿A qué persona le debes una disculpa sincera que tu orgullo te ha impedido ofrecer?',
    category: 'Emociones',
    week: 3,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-05-10T00:00:00Z',
  },
  {
    id: 'prompt-ext-122',
    prompt_text: '¿Qué vergüenza antigua estás arrastrando como si fuera un tatuaje permanente en tu identidad?',
    category: 'Emociones',
    week: 3,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-05-11T00:00:00Z',
  },
  {
    id: 'prompt-ext-123',
    prompt_text: '¿Qué emoción has censurado durante años creyendo erróneamente que era señal de debilidad?',
    category: 'Emociones',
    week: 1,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-05-12T00:00:00Z',
  },
  {
    id: 'prompt-ext-124',
    prompt_text: 'Si tu cansancio actual no fuera físico sino emocional, ¿qué te está drenando la vitalidad?',
    category: 'Emociones',
    week: 1,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-05-13T00:00:00Z',
  },
  {
    id: 'prompt-ext-125',
    prompt_text: '¿Qué alivio silencioso has experimentado recientemente que no te has permitido celebrar?',
    category: 'Emociones',
    week: 2,
    difficulty: 'suave',
    active: true,
    created_at: '2026-05-14T00:00:00Z',
  },
  {
    id: 'prompt-ext-126',
    prompt_text: '¿Qué sentimiento incómodo estás dispuesto a acompañar hoy sin intentar resolverlo de inmediato?',
    category: 'Emociones',
    week: 3,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-05-15T00:00:00Z',
  },
  {
    id: 'prompt-ext-127',
    prompt_text: '¿A quién necesitas escuchar hoy con toda tu presencia, sin interrumpir ni dar consejos no pedidos?',
    category: 'Relaciones',
    week: 1,
    difficulty: 'suave',
    active: true,
    created_at: '2026-05-16T00:00:00Z',
  },
  {
    id: 'prompt-ext-128',
    prompt_text: '¿Qué límite sano has pospuesto poner por miedo al conflicto o al rechazo?',
    category: 'Relaciones',
    week: 3,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-05-17T00:00:00Z',
  },
  {
    id: 'prompt-ext-129',
    prompt_text: '¿Qué relación te recarga de paz y cuál te deja con una sensación de vacío energético?',
    category: 'Relaciones',
    week: 2,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-05-18T00:00:00Z',
  },
  {
    id: 'prompt-ext-130',
    prompt_text: '¿Qué herida del pasado con una figura de autoridad sigue condicionando cómo tratas a tu equipo o familia?',
    category: 'Relaciones',
    week: 3,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-05-19T00:00:00Z',
  },
  {
    id: 'prompt-ext-131',
    prompt_text: '¿Qué palabra de afirmación genuina estás guardando para ti en vez de decirla a quien la necesita?',
    category: 'Relaciones',
    week: 1,
    difficulty: 'suave',
    active: true,
    created_at: '2026-05-20T00:00:00Z',
  },
  {
    id: 'prompt-ext-132',
    prompt_text: '¿A qué persona estás juzgando por un error que tú mismo has cometido con anterioridad?',
    category: 'Relaciones',
    week: 2,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-05-21T00:00:00Z',
  },
  {
    id: 'prompt-ext-133',
    prompt_text: '¿Cómo puedes ser un puerto seguro para la persona más cercana a ti durante las próximas 24 horas?',
    category: 'Relaciones',
    week: 2,
    difficulty: 'suave',
    active: true,
    created_at: '2026-05-22T00:00:00Z',
  },
  {
    id: 'prompt-ext-134',
    prompt_text: '¿En qué conversación estás pretendiendo que todo está bien cuando la relación está visiblemente agrietada?',
    category: 'Relaciones',
    week: 3,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-05-23T00:00:00Z',
  },
  {
    id: 'prompt-ext-135',
    prompt_text: '¿A quién admiras profundamente en silencio y cómo podrías honrar su ejemplo hoy?',
    category: 'Relaciones',
    week: 2,
    difficulty: 'suave',
    active: true,
    created_at: '2026-05-24T00:00:00Z',
  },
  {
    id: 'prompt-ext-136',
    prompt_text: '¿Qué máscara de perfección estás utilizando que te aleja de una intimidad real con los tuyos?',
    category: 'Relaciones',
    week: 3,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-05-25T00:00:00Z',
  },
  {
    id: 'prompt-ext-137',
    prompt_text: '¿Qué resentimiento estás listo para soltar, no por el otro, sino por la libertad de tu propia alma?',
    category: 'Relaciones',
    week: 4,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-05-26T00:00:00Z',
  },
  {
    id: 'prompt-ext-138',
    prompt_text: '¿Con quién necesitas tener una sobremesa pausada y sin teléfonos móviles esta semana?',
    category: 'Relaciones',
    week: 4,
    difficulty: 'suave',
    active: true,
    created_at: '2026-05-27T00:00:00Z',
  },
  {
    id: 'prompt-ext-139',
    prompt_text: 'Si nadie fuera a enterarse ni a aplaudirte, ¿qué obra o servicio seguirías haciendo con gusto?',
    category: 'Propósito',
    week: 2,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-05-28T00:00:00Z',
  },
  {
    id: 'prompt-ext-140',
    prompt_text: '¿Qué sufrimiento del mundo te parte el corazón de una forma que sientes el deber moral de reparar?',
    category: 'Propósito',
    week: 2,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-05-01T00:00:00Z',
  },
  {
    id: 'prompt-ext-141',
    prompt_text: '¿Cuál es el talento o don que has enterrado por cobardía o comodidad?',
    category: 'Propósito',
    week: 2,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-05-02T00:00:00Z',
  },
  {
    id: 'prompt-ext-142',
    prompt_text: 'Si hoy fuera el último año de tu capacidad creativa, ¿a qué proyecto dedicarías tus mejores horas?',
    category: 'Propósito',
    week: 2,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-05-03T00:00:00Z',
  },
  {
    id: 'prompt-ext-143',
    prompt_text: '¿En qué aspecto de tu vocación sientes que estás cumpliendo con una fidelidad auténtica?',
    category: 'Propósito',
    week: 2,
    difficulty: 'suave',
    active: true,
    created_at: '2026-05-04T00:00:00Z',
  },
  {
    id: 'prompt-ext-144',
    prompt_text: '¿Qué legado intangible quieres dejar grabado en el corazón de quienes conviven contigo?',
    category: 'Propósito',
    week: 4,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-05-05T00:00:00Z',
  },
  {
    id: 'prompt-ext-145',
    prompt_text: '¿Qué parte de tu ambición es pura vanidad y qué parte es un servicio genuino al prójimo?',
    category: 'Propósito',
    week: 2,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-05-06T00:00:00Z',
  },
  {
    id: 'prompt-ext-146',
    prompt_text: '¿Qué problema complejo te atrae de tal forma que no te importa fracasar varias veces con tal de resolverlo?',
    category: 'Propósito',
    week: 4,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-05-07T00:00:00Z',
  },
  {
    id: 'prompt-ext-147',
    prompt_text: 'Si tuvieras que resumir tu vocación en un verbo de servicio, ¿cuál elegirías?',
    category: 'Propósito',
    week: 2,
    difficulty: 'suave',
    active: true,
    created_at: '2026-05-08T00:00:00Z',
  },
  {
    id: 'prompt-ext-148',
    prompt_text: '¿Qué voz dentro de ti ha estado susurrando una dirección que tu mente analítica rechaza por miedo?',
    category: 'Propósito',
    week: 2,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-05-09T00:00:00Z',
  },
  {
    id: 'prompt-ext-149',
    prompt_text: '¿Qué estás dispuesto a sacrificar en los próximos seis meses para honrar tu llamado más alto?',
    category: 'Propósito',
    week: 4,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-05-10T00:00:00Z',
  },
  {
    id: 'prompt-ext-150',
    prompt_text: '¿En qué momento de tu semana sientes que el tiempo se detiene y estás plenamente presente?',
    category: 'Propósito',
    week: 1,
    difficulty: 'suave',
    active: true,
    created_at: '2026-05-11T00:00:00Z',
  },
  {
    id: 'prompt-ext-151',
    prompt_text: 'Describe con nitidez sensorial tu despertar ideal dentro de tres años: ¿dónde estás y qué respiras?',
    category: 'Visión',
    week: 2,
    difficulty: 'suave',
    active: true,
    created_at: '2026-05-12T00:00:00Z',
  },
  {
    id: 'prompt-ext-152',
    prompt_text: '¿Qué ritmo semanal permitiría que tu cuerpo, tu mente y tu espíritu florezcan sin agotamiento crónico?',
    category: 'Visión',
    week: 2,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-05-13T00:00:00Z',
  },
  {
    id: 'prompt-ext-153',
    prompt_text: 'Si el dinero estuviera resuelto y no fuera factor, ¿cómo estructurarías tus mañanas?',
    category: 'Visión',
    week: 2,
    difficulty: 'suave',
    active: true,
    created_at: '2026-05-14T00:00:00Z',
  },
  {
    id: 'prompt-ext-154',
    prompt_text: '¿Qué tipo de líder o mentor te gustaría llegar a ser para la siguiente generación?',
    category: 'Visión',
    week: 2,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-05-15T00:00:00Z',
  },
  {
    id: 'prompt-ext-155',
    prompt_text: '¿Qué hábitos esenciales formarán los cimientos innegociables de tu década venidera?',
    category: 'Visión',
    week: 2,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-05-16T00:00:00Z',
  },
  {
    id: 'prompt-ext-156',
    prompt_text: '¿Qué estética, orden y belleza deseas cultivar en el santuario de tu vida diaria?',
    category: 'Visión',
    week: 2,
    difficulty: 'suave',
    active: true,
    created_at: '2026-05-17T00:00:00Z',
  },
  {
    id: 'prompt-ext-157',
    prompt_text: '¿Cómo será tu relación con la tecnología en la mejor versión de tu futuro personal?',
    category: 'Visión',
    week: 2,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-05-18T00:00:00Z',
  },
  {
    id: 'prompt-ext-158',
    prompt_text: '¿Qué conversación difícil tendrás que haber superado para alcanzar la libertad que anhelas?',
    category: 'Visión',
    week: 3,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-05-19T00:00:00Z',
  },
  {
    id: 'prompt-ext-159',
    prompt_text: '¿Cuál es el estándar de calidad más elevado que estás decidido a imprimir en tu oficio?',
    category: 'Visión',
    week: 4,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-05-20T00:00:00Z',
  },
  {
    id: 'prompt-ext-160',
    prompt_text: 'Visualiza a tu yo de ochenta años mirándote hoy: ¿qué consejo urgente te daría sobre este momento?',
    category: 'Visión',
    week: 2,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-05-21T00:00:00Z',
  },
  {
    id: 'prompt-ext-161',
    prompt_text: '¿Qué creencia limitante sobre lo que es posible para ti estás dispuesto a desterrar definitivamente?',
    category: 'Visión',
    week: 3,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-05-22T00:00:00Z',
  },
  {
    id: 'prompt-ext-162',
    prompt_text: '¿Qué aspecto de tu visión requiere que dejes de esperar validación externa para comenzar?',
    category: 'Visión',
    week: 4,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-05-23T00:00:00Z',
  },
  {
    id: 'prompt-ext-163',
    prompt_text: '¿Qué excusa elegante y bien argumentada utilizas con más frecuencia para no iniciar lo que te toca?',
    category: 'Obstáculos',
    week: 3,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-05-24T00:00:00Z',
  },
  {
    id: 'prompt-ext-164',
    prompt_text: '¿Cuál es tu disparador número uno para caer en el bucle del consumo compulsivo de pantallas?',
    category: 'Obstáculos',
    week: 3,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-05-25T00:00:00Z',
  },
  {
    id: 'prompt-ext-165',
    prompt_text: '¿Qué miedo al éxito o a las consecuencias del crecimiento te mantiene escondido en la mediocridad?',
    category: 'Obstáculos',
    week: 3,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-05-26T00:00:00Z',
  },
  {
    id: 'prompt-ext-166',
    prompt_text: '¿De qué manera saboteas tus propios logros cuando las cosas empiezan a salir bien?',
    category: 'Obstáculos',
    week: 3,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-05-27T00:00:00Z',
  },
  {
    id: 'prompt-ext-167',
    prompt_text: '¿En qué área de tu vida estás esperando un rescate o una solución mágica en lugar de asumir responsabilidad?',
    category: 'Obstáculos',
    week: 3,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-05-28T00:00:00Z',
  },
  {
    id: 'prompt-ext-168',
    prompt_text: '¿Qué hábito destructivo disfrazas de recompensa o descanso al final de tu jornada?',
    category: 'Obstáculos',
    week: 3,
    difficulty: 'suave',
    active: true,
    created_at: '2026-05-01T00:00:00Z',
  },
  {
    id: 'prompt-ext-169',
    prompt_text: '¿Qué fricción innecesaria en tu entorno diario te desgasta la fuerza de voluntad antes de mediodía?',
    category: 'Obstáculos',
    week: 3,
    difficulty: 'suave',
    active: true,
    created_at: '2026-05-02T00:00:00Z',
  },
  {
    id: 'prompt-ext-170',
    prompt_text: '¿A qué persona tóxica o quejumbrosa sigues concediéndole audiencia en tus pensamientos?',
    category: 'Obstáculos',
    week: 3,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-05-03T00:00:00Z',
  },
  {
    id: 'prompt-ext-171',
    prompt_text: '¿Qué mentira te cuentas a ti mismo sobre tu falta de tiempo que un simple examen de agenda desmentiría?',
    category: 'Obstáculos',
    week: 3,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-05-04T00:00:00Z',
  },
  {
    id: 'prompt-ext-172',
    prompt_text: '¿Qué resentimiento o amargura no resuelta está bloqueando tu capacidad creativa?',
    category: 'Obstáculos',
    week: 3,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-05-05T00:00:00Z',
  },
  {
    id: 'prompt-ext-173',
    prompt_text: '¿Qué precio estás pagando hoy por haber evitado una confrontación justa hace seis meses?',
    category: 'Obstáculos',
    week: 3,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-05-06T00:00:00Z',
  },
  {
    id: 'prompt-ext-174',
    prompt_text: '¿Qué pacto secreto de mediocridad has hecho con la complacencia para no arriesgarte?',
    category: 'Obstáculos',
    week: 3,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-05-07T00:00:00Z',
  },
  {
    id: 'prompt-ext-175',
    prompt_text: '¿Cuál es la primera decisión que tomas al despertar y cómo marca la trayectoria de tu día?',
    category: 'Disciplina',
    week: 1,
    difficulty: 'suave',
    active: true,
    created_at: '2026-05-08T00:00:00Z',
  },
  {
    id: 'prompt-ext-176',
    prompt_text: '¿En qué área necesitas cambiar la motivación pasajera por un sistema rígido de hábitos?',
    category: 'Disciplina',
    week: 1,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-05-09T00:00:00Z',
  },
  {
    id: 'prompt-ext-177',
    prompt_text: '¿Qué promesa que te hiciste a ti mismo esta semana has dejado caer y cómo la repararás hoy?',
    category: 'Disciplina',
    week: 4,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-05-10T00:00:00Z',
  },
  {
    id: 'prompt-ext-178',
    prompt_text: '¿Cómo tratas a tu cuerpo en términos de nutrición, sueño e hidratación para que sostenga tu trabajo?',
    category: 'Disciplina',
    week: 1,
    difficulty: 'suave',
    active: true,
    created_at: '2026-05-11T00:00:00Z',
  },
  {
    id: 'prompt-ext-179',
    prompt_text: '¿Qué ritual de cierre de jornada necesitas implementar para no llevarte el trabajo a la cama?',
    category: 'Disciplina',
    week: 4,
    difficulty: 'suave',
    active: true,
    created_at: '2026-05-12T00:00:00Z',
  },
  {
    id: 'prompt-ext-180',
    prompt_text: '¿Cuál es tu mayor vulnerabilidad cuando estás cansado, solo, aburrido o hambriento?',
    category: 'Disciplina',
    week: 3,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-05-13T00:00:00Z',
  },
  {
    id: 'prompt-ext-181',
    prompt_text: '¿Qué libro, estudio o conocimiento profundo estás postergando por falta de constancia de lectura?',
    category: 'Disciplina',
    week: 2,
    difficulty: 'suave',
    active: true,
    created_at: '2026-05-14T00:00:00Z',
  },
  {
    id: 'prompt-ext-182',
    prompt_text: '¿Qué disciplina diaria pequeña pero inquebrantable te devolvería el respeto por tu propia palabra?',
    category: 'Disciplina',
    week: 4,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-05-15T00:00:00Z',
  },
  {
    id: 'prompt-ext-183',
    prompt_text: '¿Cómo respondes ante un imprevisto: pierdes el control del día o recalibras con serenidad?',
    category: 'Disciplina',
    week: 1,
    difficulty: 'suave',
    active: true,
    created_at: '2026-05-16T00:00:00Z',
  },
  {
    id: 'prompt-ext-184',
    prompt_text: '¿Qué actividad secundaria debes podar de inmediato para proteger tu bloque de trabajo profundo?',
    category: 'Disciplina',
    week: 4,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-05-17T00:00:00Z',
  },
  {
    id: 'prompt-ext-185',
    prompt_text: '¿Qué significa para ti hoy vivir con sobriedad y templanza en un mundo hiperestimulado?',
    category: 'Disciplina',
    week: 1,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-05-18T00:00:00Z',
  },
  {
    id: 'prompt-ext-186',
    prompt_text: '¿Cuándo fue la última vez que te maravillaste ante un detalle de la Creación sin apresurarte?',
    category: 'Espiritualidad',
    week: 1,
    difficulty: 'suave',
    active: true,
    created_at: '2026-05-19T00:00:00Z',
  },
  {
    id: 'prompt-ext-187',
    prompt_text: 'En el secreto de tu intimidad con Dios, ¿qué petición te da miedo pronunciar por temor a la respuesta?',
    category: 'Espiritualidad',
    week: 2,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-05-20T00:00:00Z',
  },
  {
    id: 'prompt-ext-188',
    prompt_text: '¿Qué ídolo moderno (dinero, estatus, seguridad, control) te está tentando a desviar tu corazón?',
    category: 'Espiritualidad',
    week: 3,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-05-21T00:00:00Z',
  },
  {
    id: 'prompt-ext-189',
    prompt_text: '¿Cómo puedes convertir una tarea cotidiana y monótona de hoy en una ofrenda de amor silencioso?',
    category: 'Espiritualidad',
    week: 4,
    difficulty: 'suave',
    active: true,
    created_at: '2026-05-22T00:00:00Z',
  },
  {
    id: 'prompt-ext-190',
    prompt_text: '¿Qué parte de tu vida necesitas soltar en las manos de Dios porque ya no tienes fuerzas para gobernarla?',
    category: 'Espiritualidad',
    week: 1,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-05-23T00:00:00Z',
  },
  {
    id: 'prompt-ext-191',
    prompt_text: '¿Qué pasaje, salmo o verdad eterna ha sido un ancla para tu mente en momentos de tempestad?',
    category: 'Espiritualidad',
    week: 2,
    difficulty: 'suave',
    active: true,
    created_at: '2026-05-24T00:00:00Z',
  },
  {
    id: 'prompt-ext-192',
    prompt_text: '¿Qué gratitud sincera brota hoy en tu interior al recordar de dónde te rescató la gracia divina?',
    category: 'Espiritualidad',
    week: 4,
    difficulty: 'suave',
    active: true,
    created_at: '2026-05-25T00:00:00Z',
  },
  {
    id: 'prompt-ext-193',
    prompt_text: 'Si el silencio es el lenguaje donde Dios habla, ¿por qué le tenemos tanto miedo a no hablar?',
    category: 'Espiritualidad',
    week: 1,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-05-26T00:00:00Z',
  },
  {
    id: 'prompt-ext-194',
    prompt_text: '¿Qué acto de generosidad discreta podrías hacer hoy sin que nadie sepa que fuiste tú?',
    category: 'Espiritualidad',
    week: 4,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-05-27T00:00:00Z',
  },
  {
    id: 'prompt-ext-195',
    prompt_text: '¿En qué área de tu corazón necesitas pedir perdón y recibir la paz que sobrepasa todo entendimiento?',
    category: 'Espiritualidad',
    week: 3,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-05-28T00:00:00Z',
  },
  {
    id: 'prompt-ext-196',
    prompt_text: '¿Cuál es la única acción que si la terminas hoy hará que todo lo demás sea más fácil o irrelevante?',
    category: 'Acción',
    week: 4,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-05-01T00:00:00Z',
  },
  {
    id: 'prompt-ext-197',
    prompt_text: 'Deja de planificar por un instante: ¿cuál es el primer paso físico de dos minutos que puedes dar ahora?',
    category: 'Acción',
    week: 4,
    difficulty: 'suave',
    active: true,
    created_at: '2026-05-02T00:00:00Z',
  },
  {
    id: 'prompt-ext-198',
    prompt_text: '¿Qué llamada, mensaje o correo electrónico difícil tienes que enviar antes de que termine el mediodía?',
    category: 'Acción',
    week: 4,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-05-03T00:00:00Z',
  },
  {
    id: 'prompt-ext-199',
    prompt_text: '¿En qué tarea estás buscando una perfección absurda que solo esconde tu temor a ser juzgado?',
    category: 'Acción',
    week: 4,
    difficulty: 'profundo',
    active: true,
    created_at: '2026-05-04T00:00:00Z',
  },
  {
    id: 'prompt-ext-200',
    prompt_text: '¿Qué compromiso con un tercero te obligaría a dejar de postergar este proyecto?',
    category: 'Acción',
    week: 4,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-05-05T00:00:00Z',
  },
  {
    id: 'prompt-ext-201',
    prompt_text: 'Si solo pudieras trabajar 90 minutos hoy por una emergencia médica, ¿qué salvarías de tu lista?',
    category: 'Acción',
    week: 4,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-05-06T00:00:00Z',
  },
  {
    id: 'prompt-ext-202',
    prompt_text: '¿Qué decisión irrevocable estás listo para tomar hoy para cerrar un ciclo agotado?',
    category: 'Acción',
    week: 4,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-05-07T00:00:00Z',
  },
  {
    id: 'prompt-ext-203',
    prompt_text: '¿Qué herramienta, recurso o persona necesitas pedir prestado para no detener tu marcha?',
    category: 'Acción',
    week: 4,
    difficulty: 'suave',
    active: true,
    created_at: '2026-05-08T00:00:00Z',
  },
  {
    id: 'prompt-ext-204',
    prompt_text: 'No te vayas a dormir sin haber ejecutado tu acción clave de hoy. ¿Cuál es exactamente y a qué hora?',
    category: 'Acción',
    week: 4,
    difficulty: 'desafiante',
    active: true,
    created_at: '2026-05-09T00:00:00Z',
  },
  {
    id: 'prompt-ext-205',
    prompt_text: 'El trabajo santifica cuando se hace con excelencia. ¿Cómo se ve la excelencia en tu próxima hora?',
    category: 'Acción',
    week: 4,
    difficulty: 'suave',
    active: true,
    created_at: '2026-05-10T00:00:00Z',
  },
];

export const EMOTIONS_CATALOG: { category: import('../types').EmotionCategory; prompt: string; description: string; color: string }[] = [
  {
    category: 'DOLOR',
    prompt: '¿Qué herida o situación te está doliendo en este momento?',
    description: 'Sensación de herida, pérdida o quebranto físico o emocional.',
    color: 'text-amber-800 bg-amber-50 border-amber-200'
  },
  {
    category: 'SOLEDAD',
    prompt: '¿En qué aspecto de tu camino te sientes incomprendido o desacompañado?',
    description: 'Aislamiento, sensación de no tener con quién compartir la carga.',
    color: 'text-sky-800 bg-sky-50 border-sky-200'
  },
  {
    category: 'TRISTEZA',
    prompt: '¿Qué pérdida, desilusión o anhelo no cumplido está detrás de esta pesadumbre?',
    description: 'Pesar del alma, duelo, melancolía por lo que fue o pudo ser.',
    color: 'text-indigo-800 bg-indigo-50 border-indigo-200'
  },
  {
    category: 'IRA',
    prompt: '¿Qué sientes que ha sido injusto, fuera de lugar o una falta de respeto?',
    description: 'Fuego ante la transgresión, frustración o impotencia.',
    color: 'text-rose-800 bg-rose-50 border-rose-200'
  },
  {
    category: 'MIEDO',
    prompt: '¿A qué desenlace le temes hoy y qué pasaría en el peor de los casos?',
    description: 'Incertidumbre ante la amenaza, anticipación del fracaso o daño.',
    color: 'text-stone-800 bg-stone-100 border-stone-300'
  },
  {
    category: 'VERGÜENZA',
    prompt: '¿Qué juicio propio o ajeno te hace querer esconderte o no dar la cara?',
    description: 'Sensación de insuficiencia, deseo de ocultarse, temor al juicio.',
    color: 'text-orange-800 bg-orange-50 border-orange-200'
  },
  {
    category: 'CULPA',
    prompt: '¿Qué estándar propio o ajeno sientes que has traicionado o incumplido?',
    description: 'Peso por una acción u omisión propia que causó daño.',
    color: 'text-purple-800 bg-purple-50 border-purple-200'
  },
  {
    category: 'ALEGRÍA',
    prompt: '¿Qué regalo, fruto o momento de gracia puedes celebrar y agradecer con gratitud hoy?',
    description: 'Gozo sincero, plenitud, celebración del bien presente.',
    color: 'text-emerald-800 bg-emerald-50 border-emerald-200'
  }
];
