-- ====================================================================
-- TRAVESÍA MIGRATION 003: STORAGE BUCKETS & SESSION RECORDINGS
-- ====================================================================

-- 1. SESSION RECORDINGS TABLE (CANONICAL METADATA)
CREATE TABLE IF NOT EXISTS public.session_recordings (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  event_id UUID REFERENCES public.events(id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  storage_path TEXT,
  file_size_bytes BIGINT,
  duration_seconds INTEGER DEFAULT 2100,
  thumbnail_path TEXT,
  uploaded_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  uploaded_at TIMESTAMPTZ DEFAULT NOW(),
  status TEXT NOT NULL DEFAULT 'AVAILABLE' CHECK (status IN ('NOT_AVAILABLE', 'PROCESSING', 'AVAILABLE', 'ERROR')),
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  duration TEXT NOT NULL DEFAULT '35 min',
  category TEXT NOT NULL DEFAULT 'El Presente',
  video_url TEXT,
  thumbnail_url TEXT,
  zoom_recording_url TEXT,
  recording_strategy TEXT NOT NULL DEFAULT 'HOSTED' CHECK (recording_strategy IN ('HOSTED', 'EXTERNAL')),
  external_url TEXT,
  views_count INTEGER DEFAULT 0,
  is_member_only BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_session_recordings_event ON public.session_recordings(event_id);
CREATE INDEX IF NOT EXISTS idx_session_recordings_date ON public.session_recordings(date DESC);
CREATE INDEX IF NOT EXISTS idx_session_recordings_status ON public.session_recordings(status);

-- 2. CREATE STORAGE BUCKETS IF NOT EXISTS (SUPABASE STORAGE SCHEMA)
-- In Supabase, buckets are managed in storage.buckets
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES 
  ('profile-images', 'profile-images', true, 5242880, ARRAY['image/png', 'image/jpeg', 'image/webp', 'image/gif']),
  ('session-recordings', 'session-recordings', false, 5368709120, ARRAY['video/mp4', 'video/quicktime', 'video/webm', 'video/x-matroska']),
  ('book-covers', 'book-covers', true, 5242880, ARRAY['image/png', 'image/jpeg', 'image/webp']),
  ('resources', 'resources', false, 104857600, ARRAY['application/pdf', 'application/epub+zip', 'image/png', 'image/jpeg']),
  ('content-media', 'content-media', true, 52428800, ARRAY['image/png', 'image/jpeg', 'image/webp', 'video/mp4'])
ON CONFLICT (id) DO UPDATE SET
  public = EXCLUDED.public,
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

-- 3. STORAGE ROW LEVEL SECURITY POLICIES

-- Enable RLS on storage.objects
ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;

-- 3.1 Profile Images: Publicly readable; Users can upload/update/delete only in their own folder
CREATE POLICY "Profile images are publicly viewable"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'profile-images');

CREATE POLICY "Authenticated users can upload own profile image"
  ON storage.objects FOR INSERT
  WITH CHECK (
    bucket_id = 'profile-images' 
    AND auth.role() = 'authenticated'
  );

CREATE POLICY "Users can update own profile image"
  ON storage.objects FOR UPDATE
  USING (
    bucket_id = 'profile-images' 
    AND auth.uid()::text = (storage.foldername(name))[1]
  );

-- 3.2 Session Recordings: STRICTLY PRIVATE BUCKET
-- Direct public select is completely denied.
-- Only admins can directly read/write storage objects.
-- Members access files strictly via temporary signed URLs generated by backend.
CREATE POLICY "Admins have full access to session recordings storage"
  ON storage.objects FOR ALL
  USING (
    bucket_id = 'session-recordings'
    AND public.is_admin(auth.uid())
  );

-- 3.3 Book Covers & Content Media: Publicly readable; Admin writable
CREATE POLICY "Book covers are publicly viewable"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'book-covers' OR bucket_id = 'content-media');

CREATE POLICY "Admins can manage book covers and media"
  ON storage.objects FOR ALL
  USING (
    (bucket_id = 'book-covers' OR bucket_id = 'content-media')
    AND public.is_admin(auth.uid())
  );

-- 3.4 Resources: Authenticated members can read; Admin can manage
CREATE POLICY "Members can view resources"
  ON storage.objects FOR SELECT
  USING (
    bucket_id = 'resources'
    AND auth.role() = 'authenticated'
  );

CREATE POLICY "Admins can manage resources files"
  ON storage.objects FOR ALL
  USING (
    bucket_id = 'resources'
    AND public.is_admin(auth.uid())
  );
